### ISSUE TITLE
Add support for dynamic station playlists in mopidy-pandora

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-pandora#2]
Regarding the dependency for Mopidy to support dynamic playlists (comment at https://github.com/mopidy/mopidy/issues/712#issuecomment-68020556 and reference to https://github.com/mopidy/mopidy/issues/620):

Will the same issue not have been resolved in https://github.com/mopidy/mopidy-spotify.git? I don't have a Spotify premium account so cannot compare the functionality, but assume Spotify also creates playlists on the fly?

**Comment by jcass77** [comment]
I've had a look a the spec doc. It seems that the new [on_tag]
(https://github.com/mopidy/mopidy/blob/983148a9a42cb110de80574801aff532ce917e7d/mopidy/audio/actor.py#L393-397) method that was addd to ```actor.py``` a few days ago might be the beginnings of offering support for updating track metadata using eventing?

It doesn't look like this is supported in the ```core``` package or anywhere elsewhere at the moment though.

**Comment by m0ngr31** [comment]
So currently there isn't a way to see the current track playing or scrobble it at all?

**Comment by jcass77** [comment]
No unfortunately not.

**Comment by jcass77** [comment]
Not much consolation, but the song and artist details should now at least be written to the log file on each track change, once https://github.com/rectalogic/mopidy-pandora/pull/23 has been merged.

**Comment by jcass77** [comment]
The v0.2.0 release in the 'develop' branch now includes a front-end extension that automatically expands the tracklist by adding additional Pandora tracks as required.

This means that all of the track information is now displayed (song / artist name, track length, bitrate, images, etc) and that the tracks will scrabble to last.fm correctly.
