### ISSUE TITLE
Add support to rate tracks in Pandora (love / ban)

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-pandora#4]
One of the major attractions of Pandora is its ability to learn what the listener's preferences are. I find that I miss not being able to refine this further using the thumbs up / down features when listening in Mopidy.

Although not strictly part of the Mopidy API, my question is whether it would be possible to enable these features in the back-end in case any web clients would like to expose this functionality in the UI.

![skitched-20150309-171928](https://cloud.githubusercontent.com/assets/10268911/6557799/7f426f56-c680-11e4-9952-c1f3e15676f3.png)

I will start working on a pull request if anybody is in support of the idea, and feels that this is worth investigating / pursuing.

**Comment by rectalogic** [comment]
Would you do this by having the front end "play" a special uri that indicates to "like" the current track? How will the front end know which backends support doing this, or even how to construct the uri for a track on a specific backend? You might want to look at extending the mopidy backend api to support something like this generically maybe the Playback provider interface? https://docs.mopidy.com/en/latest/api/backends/#playback-provider

**Comment by jcass77** [comment]
I'm not quite sure what the best way would be to make a web client 'backend-aware'. For now I am hoping that it will be possible to check which backends are installed using something like ```mopidy.ext.Registry```, and just toggle which controls are rendered in the UI (but I haven't looked into this yet).

Yes I do think that the new methods will have to go into the mopidy-pandora playback provider. Right now I am trying to figure out how to expose these to the JavaScript engine so that it is callable by the web client. Mopidy uses introspection to create JavaScript functions for all of the standard stuff in the core (see ```getApiSpec``` in ```mopidy.js```). But I haven't been able to figure out how to extend this for any new methods that we add to ```PandoraPlaybackProvider```.

**Comment by rectalogic** [comment]
I meant add the new methods to the base backend.PlaybackProvider interface and then mopidy-pandora would implement them. I don't think you would want the front ends to know all about a specific backend. There should be a generic way to "rate" via PlaybackProvider and backends can implement that if they support it.

**Comment by jcass77** [comment]
Yes adding to the base backend.PlaybackProvider would be great, and it will probably depend on whether the developers believe that the usecase is common enough to justify that approach.

I think that there will probably always be features that are unique to a particular backend or service however, so we may not be able to cover them all in which case providing a framework for this type of extension may be more preferable than adding to to the base implementation.

**Comment by jcass77** [comment]
I haven't been able to figure out how to make JSON RPC calls to our own PlaybackProvider (which is what I think will be required to trigger the ratings change for tracks).

It looks like the service framework proposed here https://github.com/liamw9534/mopidy/pull/2 should be a step in the right direction. But it hasn't been merged yet.

Moped also does something similar [here](https://github.com/martijnboland/moped/blob/master/src/app/services/mopidyservice.js).  But that is using Angular.

Back to the drawing board...

**Comment by jcass77** [comment]
While we're hoping for the Mopidy service framework to land, I've started to maintain a truly horrible hack for implementing ratings using a rudimentary 'double-click' implementation.

It is available on a separate branch here: https://github.com/jcass77/mopidy-pandora/tree/feature/thumbs_support

The hacks can be activated by double clicking the pause/play button, or pause/next, pause/back. Perhaps this will stimulate some discussion and ideas that we can improve on...

**Comment by jcass77** [comment]
Update: the experimental eventing support has now landed in the main 'develop' branch. It is functional, but there are still a few limitations:

- there are no visual queues as to whether a track has been rated before.
- apart from info messages sent to the log file, there is no way to tell if an event has been caught and processed successfully 
- invoking an event always requires the user to click 'play/resume' again for the song to continue, or the next song to start playing.

**Comment by jcass77** [comment]
Closing this as we have a working implementation in the current v0.1.7 release. Will also work in v0.2.0 once https://github.com/mopidy/mopidy/issues/1352 is fixed.
