### ISSUE TITLE
Cannot import name 'compat' from 'mopidy'

### ISSUE THREAD

**Issue by kirkpensalvo** [mopidy/mopidy-pandora#76]
Installed Mopidy-Pandora and setup config, upon restart get the following:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_pandora/__init__.py", line 88, in setup
    from .backend import PandoraBackend
  File "/usr/local/lib/python3.7/dist-packages/mopidy_pandora/backend.py", line 14, in <module>
    from mopidy_pandora.library import PandoraLibraryProvider
  File "/usr/local/lib/python3.7/dist-packages/mopidy_pandora/library.py", line 15, in <module>
    from mopidy_pandora.uri import (
  File "/usr/local/lib/python3.7/dist-packages/mopidy_pandora/uri.py", line 7, in <module>
    from mopidy import compat, models
ImportError: cannot import name 'compat' from 'mopidy' (/usr/lib/python3/dist-packages/mopidy/__init__.py)

**Comment by txomon** [comment]
@kirkpensalvo I think the last released version of this extension is not compatible with the latest mopidy. Would you mind installing this repo's `master` branch and see if you still hit the problem? From what I can see the `master` doesn't contain `from mopidy import compat` anymore.

**Comment by kingosticks** [comment]
Did this just never see a PyPi release after the Python 3 updates it got in July? Were we waiting on someone in the US with Pandora access to test or can we just cut a release, @jodal?

**Comment by kirkpensalvo** [comment]
@txomon Yep, had to pull the master (noticed the change in source too) and had to pull the latest for pydora as well (models don't match the latest). Works now. @kingosticks Definitely still the old version(s) on PyPi.

**Comment by jodal** [comment]
I can cut a release, but I don't seem to have access to the PyPI registration for Mopidy-Pandora.

@jcass77 @rectalogic Can you please add "jodal", "adamcik", and "kingosticks" as owners of Mopidy-Pandora on PyPI? You can do it here: https://pypi.org/manage/project/mopidy-pandora/collaboration/

**Comment by jodal** [comment]
@kirkpensalvo Thanks for testing out the upgraded version of the extension and confirming that it still works!

**Comment by jcass77** [comment]
...sent invitations to add "jodal", "adamcik", and "kingosticks" as PyPI owners.

**Comment by jodal** [comment]
Thanks! I uploaded an 1.0.0 release now, which should fix this issue.
